travis:
  secure:
    BINSTAR_TOKEN: kW9qW5HlGa3PKW9+BVlmFpGZ1MWdU74UNEMuHfOpmaYjafJhGt2yQ0dUhHICv90/Ob6mkqZAI7VGXxvJfQS/AdpowZQ2T3OW50zI4w4nTA1OHsaB+4KVQND+2chliEzN5UfcVDvcxgPRvMoYoGS9A5lbwD57HiwJ0YuzoRahQMonjTjSFWnJTHZK+x69OBqyVUlCaXbxWMGq/ULhPyGsJ0NHBSDf93OpakvZnd9E+V+GsV7n8GtgXUVYKYNpscGw4XgCIPHLg3aJYnAvCsaefghFRAYAT+i88/eFWJm+rRx59N36Ui0/pQkgaHuurZKGns9f7ajkaJF7JJNpsM++EwsVhhYHDjZRuk+HQTCS+Pq/CSprACPMfiQkERFrTQsT44Rm+IbPzyKGm+UmxILfJ1xJEZiAqcmGT6WYgatGQLG1tKO0ZnY+1Gerl35zdVI3F9F9dbQd7aa5MbquBjI6G0eancD3Jumm7I/hJnLrxY8RbyU2aK7YyGwcDKhvKq5IbxWKzT7OZ7brunhbHs9aB3lY3z90Mhm0RQVaqoi3zgJP1HkhKd48PayHAvxA1KWt4sdD1v9eU77NvreEew+REnXw2BR6Ae89CAh3c76rPnPoDtWHrWIKZuOKxKnDz23RGsqBmGdXkK23i9dLgE6QPBdiP/L+O3D+r0bD6a4MEGc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
